name: Instance Rebooting

on:
  branch_protection_rule:
    types: [created, edited]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  login_reboot:
  
    runs-on: ubuntu-latest

    steps:

      - run: apt install -y zip
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}

      - run: ssh ${{ steps.ssh.outputs.SERVER }}  "cd /home; ls -altr; reboot now;"


          








                        
