name: Instance Rebooting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PATH: /home
  
jobs:
  
  login_reboot:
  
    runs-on: ubuntu-latest

    steps:

      - name: Install Dep
        run: |
          apt-get update && upgrade
          apt-get install zip
          apt-get install tar
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}

      - run: ssh ${{ steps.ssh.outputs.SERVER }}  "cd $PATH; ls -altr; reboot now;"


          








                        
